varsion: '3.8'

services:

    db:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      enviroment:
           MYSQL_ROOT_PASSWORD: test
   www:
    depends_on:
       - db
    image: php:7.4.18.-apache
    volumes:
     - "./php-dat/:/var/www/html"
    ports
    - 80:80
    - 443:443
