version: "3.1"

services: 

    db:
        image: mariadb:latest
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        volumes: 
            - ./data_db:/var/lib/mysql
    
    web:
        hostname: web
        image: wordpress:latest
        depends_on: 
            - db
        ports: 
            - "8080:80"
        environment: 
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=root
        volumes: 
            - ./plugins:/var/www/html/wp-content/plugins
            - ./themes:/var/www/html/wp-content/themes
            - ./uploads:/var/www/html/wp-content/uploads
