version: "3.9"

services:
  
  nginx:
      image: nginx:latest
      container_name: nginx-server
      ports:
       - "80:80"
      depends_on:
          - php
      volumes:
           - ./nginx/default:/etc/nginx/sites-available/default
           - ./nginx/default:/etc/nginx/sites-enabled/default
           - ./logs/error.log:/var/log/nginx/error.log
           - ./logs/access.log:/var/log/nginx/access.log
      networks:
          - lemp-server
  
  db:
    image: mariadb
    container_name: mariadb-data
    volumes:
        - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    networks:
        - lemp-server   
  php:

    image: php:fpm
    container_name: php
    ports:
      - "9000:9000"
    volumes:
       - ./public:/var/lib/www/html
    networks:
        - lemp-server
     
  
  phpmyadmin:
  
       image: phpmyadmin/phpmyadmin
       container_name: php-myadmin
       restart: always
       ports:
        - "9090:80"
       depends_on:
           - db
       environment:
             PMA_HOST: db
             MYSQL_ROOT_PASSWORD: root
       networks:
            - lemp-server

networks:
     lemp-server:
volumes:
   logs:
   nginx:
   public:
   db_data:
   
